[AE-158] Specify compatible sketches for each `fqbn:`
arduino-libraries/Arduino_UnifiedStorage pull request #13
Opened 2023-09-05 09:33 UTC by aliphys

Due to differences in architecture and physical implementation (e.g. no SD slot on the Opta) not all examples in this library are supposed to work with all architectures. In this PR, we use the following scheme to define for which `fqbn:` which examples should be checked.
```
include:
  - board:
    additional-sketch-path: |
      - example/SketchA
      - example/SketchB
```

We define a `UNIVERSAL_SKETCH_PATH` that includes the location of the test sketches in `extras/tests`. These tests should work for all platforms. `matrix.additional-sketch-paths` references the sketches for each fqbn.

2023-09-05 10:02 UTC, aliphys commented
Test sketches in [extras/tests](https://github.com/arduino-libraries/Arduino_UnifiedStorage/tree/7c3dd7234b31d8816099a75ab0cb8e171b059ace/extras/tests) compile status as of https://github.com/arduino-libraries/Arduino_UnifiedStorage/pull/13/commits/7c3dd7234b31d8816099a75ab0cb8e171b059ace :
- ✅ `arduino:mbed_portenta:envie_m7`
- ❌ `arduino:renesas_portenta:portenta_c33`-> `Error: Process completed with exit code 1.` ->[Log](https://github.com/arduino-libraries/Arduino_UnifiedStorage/actions/runs/6082915929/job/16501698646#step:3:951)
- ❌ `arduino:mbed_opta:opta` -> `Error: Process completed with exit code 1.`-> [Log](https://github.com/arduino-libraries/Arduino_UnifiedStorage/actions/runs/6082915929/job/16501698933#step:3:539)

2023-09-05 10:11 UTC, aliphys commented
Merging https://github.com/arduino-libraries/Arduino_UnifiedStorage/pull/9 should fix compilation issues on C33 and Opta.

2023-09-05 12:48 UTC, per1234 requested changes

2023-09-05 12:48 UTC, per1234 commented on .github/workflows/compile-examples.yml
> +                - examples/BackupInternalPartitions
```suggestion
              fqbn: arduino:mbed_portenta:envie_m7
            additional-sketch-paths: |
              - examples/SimpleStorageWriteRead
              - examples/PortentaH7Logger
              - examples/AdvancedUSBInternalOperations
              - examples/BackupInternalPartitions
          - board:
              fqbn: arduino:renesas_portenta:portenta_c33
            additional-sketch-paths: |
              - examples/SimpleStorageWriteRead
              - examples/AdvancedUSBInternalOperations
              - examples/BackupInternalPartitions
          - board:
              fqbn: arduino:mbed_opta:opta
            additional-sketch-paths: |
              - examples/SimpleStorageWriteRead
              - examples/AdvancedUSBInternalOperations
              - examples/BackupInternalPartitions
```

Fix the data structure of [`jobs.<job_id>.strategy.matrix.include`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude)

---

Alternatively, you can just add the `additional-sketch-paths` data directly under the matrix elements in `jobs.build.strategy.matrix.board`. `jobs.<job_id>.strategy.matrix.include` is useful in cases where you want to apply the same sub-configuration to the matrix jobs of multiple boards, but in this case where you are configuring each matrix job individually, there is no benefit to balance out the increased complexity of the workflow code.

2023-09-05 12:48 UTC, per1234 commented on .github/workflows/compile-examples.yml
> +                - examples/BackupInternalPartitions
I notice these three sketches are compiled for all the boards. If the are intended to be compatible with any of the boards supported by the library, the paths can be moved to `env.UNIVERSAL_SKETCH_PATHS`

2023-09-06 15:13 UTC, merged

2023-09-06 20:30 UTC, aliphys commented
> Merging https://github.com/arduino-libraries/Arduino_UnifiedStorage/pull/9 should fix compilation issues on C33 and Opta.

If the compilation issue were fixed, which commit was it? The https://github.com/arduino-libraries/Arduino_UnifiedStorage/pull/9  PR mentioned is still open. I wanted to make sure the `compile-sketches` workflow is compatible with the changes prior to merging :)

2023-09-07 10:02 UTC, aliphys commented
@per1234 's changes merged into the main branch as part of https://github.com/arduino-libraries/Arduino_UnifiedStorage/pull/16. ✅